version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node

  working_directory: ~/app





jobs:
  commitlint:
    docker:
      - image: williamlauze/circleci-commitlint:latest
    working_directory: ~/app

    steps:
      - checkout
      - run:
          name: Lint commit messages
          command: /bin/sh /.scripts/commitlint_range.sh

  checkout:
    <<: *defaults

    steps:
      - restore_cache:
          name: Restore Repository Cache
          keys:
            - repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - repo-{{ .Branch }}
            - repo-master
            - repo-

      - checkout

      - save_cache:
          name: Save Repository Cache
          key: repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .

      - persist_to_workspace:
          root: .
          paths:
            - .

  install-dependencies:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-{{ checksum "yarn.lock" }}
            - yarn-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - restore_cache:
          name: Restore Build Cache
          keys:
            - build-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - build-{{ .Branch }}
            - build-master
            - build-

      - run:
          name: Build the site
          command: yarn build && yarn export

      - save_cache:
          name: Save Build Cache
          key: build-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - out

      - persist_to_workspace:
          root: .
          paths:
            - out

  # lint:
  #   <<: *defaults

  #   steps:
  #     - attach_workspace:
  #         at: .

  #     - run:
  #         name: Lint styles
  #         command: npx stylelint scss/*

  # test:
  #   <<: *defaults

  #   steps:
  #     - attach_workspace:
  #         at: .

  #     - run:
  #         name: Add Yarn Binary Folder To $PATH
  #         command: export PATH="$PATH:`yarn global bin`"

  #     - run:
  #         name: Run tests
  #         command: yarn test

  # coverage:
  #   <<: *defaults

  #   steps:
  #     - attach_workspace:
  #         at: .

  #     - run:
  #         name: Add Yarn Binary Folder To $PATH
  #         command: export PATH="$PATH:`yarn global bin`"

  #     - run:
  #         name: Generate and upload coverage report
  #         command: yarn test-coverage

  deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - add_ssh_keys

      - run:
          name: Setup the bot's Git credentials
          command: >
            git config user.email "bot@circleci.com" &&
            git config user.name "CircleCI"

      - run:
          name: Create a temporary branch
          command: git checkout -b foo

      - run:
          name: Commit the build directory
          command: >
            git add out &&
            git commit -m 'Deploy the site'

      - run:
          name: Deploy the static site
          command: yarn deploy





workflows:
  version: 2

  main:
    jobs:
      - checkout
      - commitlint
      - install-dependencies:
          requires:
            - checkout
      # - test:
      #     requires:
      #       - install-dependencies
      # - coverage:
      #     requires:
      #       - install-dependencies
      # - lint:
      #     requires:
      #       - install-dependencies
      - build:
          requires:
            - install-dependencies
      - deploy:
          requires:
            - commitlint
            - build
            # - lint
            # - test
          filters:
            branches:
              only: develop
